# This workflow will run when a new tag starting with 'v' is created and retag the image for the matching commit.
# For more information see: https://stackoverflow.com/questions/63932728/github-action-release-tag

name: Release Application

on:
  push:
    tags:
      - 'v*' # Should this be 'v*.*.*'?

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    #- name: Check out the repo
    #  uses: actions/checkout@v2

    - name: Get the git commit short hash
      id: git_commit_info
      run: |
        echo "::set-output name=short_sha::$(echo ${GITHUB_SHA} | cut -c1-8)"
        echo "::set-output name=version::${GITHUB_REF#refs/tags/}"

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      id: docker_image_pull
      run: docker pull cicdexamples/colorexample:${{ steps.git_commit_info.outputs.short_sha }}

    - name: Retag the Docker image
      id: docker_image_retag
      run: docker tag cicdexamples/colorexample:${{ steps.git_commit_info.outputs.short_sha }} cicdexamples/colorexample:${{ steps.git_commit_info.outputs.version }}

    - name: Push the Docker image
      id: docker_image_push
      run: docker push cicdexamples/colorexample:${{ steps.git_commit_info.outputs.version }}
